//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_FS : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean MoveForward
        {
            get
            {
                return SteamVR_Actions.fS_MoveForward;
            }
        }
        
        public virtual SteamVR_Action_Boolean MoveBackward
        {
            get
            {
                return SteamVR_Actions.fS_MoveBackward;
            }
        }
        
        public virtual SteamVR_Action_Boolean UIControlRight
        {
            get
            {
                return SteamVR_Actions.fS_UIControlRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean UIControlLeft
        {
            get
            {
                return SteamVR_Actions.fS_UIControlLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean UISubmit
        {
            get
            {
                return SteamVR_Actions.fS_UISubmit;
            }
        }
    }
}
